### ISSUE TITLE
Add get started Btn to top

### ISSUE THREAD

**Issue by LordFarquhar** [MichaelGrigoryan25/chattly-app#5]
**Describe the solution you'd like**
Love the clean landing page but now I've been there once I've read all the info and want to get straight into chatting
There could be an additional Start Now button in one of the top corners of the page so returners do not have to go through the entire scroll animation now that they have already read the info

**Additional context**
![image](https://user-images.githubusercontent.com/65400619/82348953-66daba00-99f1-11ea-8c41-0c68a1196561.png)

**Comment by MichaelGrigoryan25** [comment]
@LordFarquhar please post this issue on the [chattly](https://github.com/MichaelGrigoryan25/chattly) repository not chattly-app.
